#!/bin/bash

if (( $# < 2 ))
then
	echo "SYNTAX: $0 <AWS profile name> <playbook>"
	exit 1
fi

profile=$1
playbook=$2

access_key=$(grep -A3 $profile ~/.aws/credentials | grep aws_access_key_id | awk '{print $3}')
secret_key=$(grep -A3 $profile ~/.aws/credentials | grep aws_secret_access_key | awk '{print $3}')
session_token=$(grep -A3 $profile ~/.aws/credentials | grep aws_session_token | awk '{print $3}')

AWS_ACCESS_KEY=$access_key
AWS_SECRET_KEY=$secret_key
AWS_SESSION_TOKEN=$session_token

export AWS_ACCESS_KEY AWS_SECRET_KEY AWS_SESSION_TOKEN
export SSH_ANSIBLE_PRIVATE=/Users/thomasmoran/.ssh/aws-academy-virginia.pem
export PYTHON_INTERPRETER=/Users/thomasmoran/play/ansible/bin/python
export AWS_SSH_KEY=tomWorking

ansible-playbook -i environments/dev $playbook
