- name: Launch EC2 Instance
  ec2:
    key_name: "{{ aws_key_name }}"
    instance_type: "{{ ec2_type }}"
    image: "{{ image_id }}"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ subnet_id }}"
    group_id: "{{ secgrpids }}"
    assign_public_ip: yes
    instance_profile_name: "{{ iam_role }}"
    wait: yes
    instance_tags:
      Name: "{{ instance_name }}"
      Project: "{{ project_name }}"
      Environment: "{{ aws_environment }}"
  when: groups['servers'] | length == 0
  register: ec2

- name: Wait for Connection
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 30
    timeout: 180
  with_items: "{{ ec2.instances }}"
  when: groups['servers'] | length == 0

- name: Add host to inventory
  lineinfile:
    dest: "{{ playbook_dir }}/environments/{{ aws_environment }}/hosts"
    insertafter: '^\[servers\]'
    line: "{{ item.public_dns_name }}"
  when: groups['servers'] | length == 0
  with_items: "{{ ec2.instances }}"

- name: Refresh inventory
  meta: refresh_inventory

- name: Show public IP, DNS and Instance ID
  debug:
    msg:
      - "Public IP: {{ item.public_ip }}"
      - "Public DNS name: {{ item.public_dns_name }}"
      - "Instance ID: {{ item.id }}"
  with_items: "{{ ec2.instances }}"
  when: groups['servers'] | length == 0
